name: Publish Website
on:
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
        - name: Prep
          uses: actions/setup-node@v1
          with:
            node-version: '14'
        - name: Checkout
          uses: actions/checkout@v2
        - run: |
            npm install
            npm run build
            git config user.name github-actions
            git config user.email github-actions@github.com

            git clone --single-branch --branch gh-pages git@github.com:codeimpossible/jaredbarboza.me.git gh-pages
            cp -R ./dist/. ./gh-pages/
            cd gh-pages
            git add -A
            count=$(git diff --cached --numstat | wc -l | xargs)
            if [[ "$count" != "0" ]]; then
                git commit -m 'automatic deploy'
                git push
            fi
