name: Publish Website
on:
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
        - name: Prep
          uses: actions/setup-node@v1
          with:
            node-version: '14'
        - name: Checkout & Build
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.PAT }}
        - run: |
            npm install
            npm run build
        - name: Stage changes
          id: stage
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.PAT }}
            path: 'gh-pages'
            ref: 'refs/heads/gh-pages'
            fetch-depth: 0
            persist-credentials: false
        - run: |
            cp -R ./dist/. ./gh-pages/
            cd gh-pages
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add -A
            count=$(git diff --cached --numstat | wc -l | xargs)
            if [[ "$count" != "0" ]]; then
                git commit -m "automated site deploy. $count changes."
                echo "::set-output name=has_changes::$(echo 'true')"
            else
                echo "Nothing to do. Exiting."
                echo "::set-output name=has_changes::$(echo 'false')"
            fi
        - name: Push changes
          if: steps.stage.outputs.has_changes == 'true'
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.PAT }}
            branch: 'gh-pages'
            directory: './gh-pages'
