name: Publish Website
on:
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
        - name: Prep
          uses: actions/setup-node@v1
          with:
            node-version: '14'
        - name: Checkout & Build
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.PAT }}
        - run: |
            npm install
            npm run build
        - name: Checkout & Build
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.PAT }}
            path: 'gh-pages'
            ref: 'refs/heads/gh-pages'
            fetch-depth: 1
        - run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            cp -R ./dist/. ./gh-pages/
            cd gh-pages
            git add -A
            count=$(git diff --cached --numstat | wc -l | xargs)
            if [[ "$count" != "0" ]]; then
                git commit -m "automated site deploy. $count changes."
                git push
            else
                echo "Nothing to do. Exiting."
            fi
